### ISSUE TITLE
作者考虑支持一下lua吗，用lede/qwrt装不上，那边还是用的21.02

### ISSUE THREAD

**Issue by milkman-wang** [makeding/luci-app-fleth#1]
因为想用硬路由，所以只能用lean的qwrt，但是折腾了很久mape都失败了，然后搜到作者的脚本发现是新主线用的js，装不上，所以恳求作者能支持一下lua，感谢🙏（已starred）

**Comment by missing233** [comment]
如果你用的是1G NTT，qwrt的mapcalc获取不到前缀的。建议去lede那边提issue

**Comment by makeding** [comment]
emmmm lua 我不太会写主要是

你这可以先用命令模式凑合一下：

vi /etc/config/fleth

```
option enabled '1'
option ip6prefix_enabled '1'
```

然后执行 `fleth` 命令。

**Comment by milkman-wang** [comment]
> 如果你用的是1G NTT，qwrt的mapcalc获取不到前缀的。建议去lede那边提issue

大佬所以10G的话可以吗，这样我就换10G的好了

**Comment by milkman-wang** [comment]
> emmmm lua 我不太会写主要是
> 
> 你这可以先用命令模式凑合一下：
> 
> vi /etc/config/fleth
> 
> ```
> option enabled '1'
> option ip6prefix_enabled '1'
> ```
> 
> 然后执行 `fleth` 命令。

感谢大佬
